dist: bionic

language: go

go_import_path: github.com/DNAProject/DNA

os:
  - linux
  - osx

go:
  - 1.12.x

script:
  - env GO111MODULE=on make DNA
  - env GO111MODULE=on go mod vendor
  - bash ./.travis.check-license.sh
  - bash ./.travis.gofmt.sh
  - bash ./.travis.gotest.sh
  - base ./.travis.deploy.sh

deploy:
  provider: releases
  token: "${GITHUB_TOKEN}"
  file_glob: true
  file:
    - dnaNode*
  skip_cleanup: true
  overwrite: true
  draft: true
  on:
    repo: DNAProject/DNA
    tags: true
